version: "3.9"

services:
  edgedb:
    image: edgedb/edgedb:3.4
    restart: unless-stopped
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DOCKER_LOG_LEVEL: trace
    volumes:
      - "./dbschema:/dbschema"
      - "myapp:/var/lib/edgedb/data"
    ports:
      - "5757:5656"

volumes:
  myapp: