// GENERATED by @edgedb/generate v0.3.4

import type {Executor} from "edgedb";


export type GetUserReturns = {
  "id": string;
  "name": string;
}[];

export async function getUser(client: Executor): Promise<GetUserReturns> {
  return client.query(`\
select User {
    id,
    name
}`);

}
